// Curated institution aliases; exact normalized matching avoids ambiguous substring matches.
const entries: [string, string[]][] = [
 ['普林斯顿大学',['普林斯顿','Princeton University','Princeton']],
 ['哈佛大学',['哈佛','Harvard University','Harvard']],
 ['耶鲁大学',['耶鲁','Yale University','Yale']],
 ['斯坦福大学',['斯坦福','Stanford University','Stanford','Standord University','Standord','Standford University','Standford']],
 ['麻省理工学院',['麻省理工','MIT','Massachusetts Institute of Technology']],
 ['加州理工学院',['加州理工','Caltech','California Institute of Technology']],
 ['哥伦比亚大学',['哥伦比亚','Columbia University','Columbia']],
 ['宾夕法尼亚大学',['宾大','宾夕法尼亚','UPenn','University of Pennsylvania','Penn']],
 ['布朗大学',['布朗','Brown University','Brown']],
 ['达特茅斯学院',['达特茅斯','Dartmouth College','Dartmouth']],
 ['康奈尔大学',['康奈尔','Cornell University','Cornell']],
 ['芝加哥大学',['芝加哥','University of Chicago','UChicago']],
 ['杜克大学',['杜克','Duke University','Duke']],
 ['西北大学',['西北','Northwestern University','Northwestern']],
 ['约翰斯·霍普金斯大学',['约翰斯霍普金斯大学','约翰霍普金斯大学','约翰斯霍普金斯','霍普金斯','Johns Hopkins University','Johns Hopkins','JHU']],
 ['莱斯大学',['莱斯','Rice University','Rice']],
 ['范德堡大学',['范德堡','Vanderbilt University','Vanderbilt']],
 ['圣母大学',['圣母','University of Notre Dame','Notre Dame']],
 ['圣路易斯华盛顿大学',['华盛顿大学圣路易斯分校','Washington University in St. Louis','Washington University in Saint Louis','WashU','WUSTL']],
 ['华盛顿大学',['University of Washington','华盛顿大学西雅图分校']],
 ['乔治华盛顿大学',['George Washington University','GWU']],
 ['纽约大学',['纽约','New York University','NYU']],
 ['南加州大学',['南加大','南加州','University of Southern California','USC']],
 ['加州大学洛杉矶分校',['加州大学洛杉矶','加州洛杉矶','UCLA','UC Los Angeles','University of California Los Angeles','University of California, Los Angeles']],
 ['加州大学伯克利分校',['加州大学伯克利','伯克利大学','伯克利','UC Berkeley','UCB','University of California Berkeley','University of California, Berkeley']],
 ['加州大学圣地亚哥分校',['UCSD','UC San Diego','University of California, San Diego','加州大学圣迭戈分校']],
 ['加州大学戴维斯分校',['UCD','UC Davis','University of California, Davis']],
 ['加州大学欧文分校',['加州大学尔湾分校','UCI','UC Irvine','University of California, Irvine']],
 ['加州大学圣塔芭芭拉分校',['加州大学圣巴巴拉分校','UCSB','UC Santa Barbara','University of California, Santa Barbara']],
 ['密歇根大学安娜堡分校',['密歇根大学','密大','University of Michigan','University of Michigan Ann Arbor','UMich']],
 ['卡内基梅隆大学',['卡内基梅隆','Carnegie Mellon University','Carnegie Mellon','CMU']],
 ['埃默里大学',['埃默里','Emory University','Emory']],
 ['乔治城大学',['乔治城','Georgetown University','Georgetown']],
 ['弗吉尼亚大学',['弗吉尼亚','University of Virginia','UVA']],
 ['北卡罗来纳大学教堂山分校',['北卡教堂山','UNC Chapel Hill','University of North Carolina at Chapel Hill']],
 ['佐治亚理工学院',['佐治亚理工','Georgia Institute of Technology','Georgia Tech']],
 ['德克萨斯大学奥斯汀分校',['得克萨斯大学奥斯汀分校','UT Austin','University of Texas at Austin']],
 ['伊利诺伊大学厄巴纳-香槟分校',['伊利诺伊大学香槟分校','UIUC','University of Illinois Urbana-Champaign','University of Illinois at Urbana-Champaign']],
 ['波士顿大学',['波士顿','Boston University','BU']],
 ['波士顿学院',['Boston College','BC']],
 ['塔夫茨大学',['塔夫茨','Tufts University','Tufts']],
 ['东北大学',['Northeastern University','Northeastern']],
 ['罗切斯特大学',['罗切斯特','University of Rochester']],
 ['威斯康星大学麦迪逊分校',['威斯康星麦迪逊','University of Wisconsin-Madison','UW Madison']],
 ['宾夕法尼亚州立大学',['宾州州立','宾州州立大学','Pennsylvania State University','Penn State','PSU']],
 ['普渡大学',['普渡','Purdue University','Purdue']],
 ['俄亥俄州立大学',['俄亥俄州立','Ohio State University','The Ohio State University']],
 ['佛罗里达大学',['佛罗里达','University of Florida','UF']],
 ['威廉姆斯学院',['威廉姆斯','Williams College','Williams']],
 ['阿默斯特学院',['阿默斯特','Amherst College','Amherst']],
 ['斯沃斯莫尔学院',['斯沃斯莫尔','Swarthmore College','Swarthmore']],
 ['波莫纳学院',['波莫纳','Pomona College','Pomona']],
 ['韦尔斯利学院',['韦尔斯利','Wellesley College','Wellesley']],
 ['鲍登学院',['鲍登','Bowdoin College','Bowdoin']],
 ['米德尔伯里学院',['明德学院','米德尔伯里','Middlebury College','Middlebury']],
 ['卡尔顿学院',['卡尔顿','Carleton College','Carleton']],
 ['克莱蒙特麦肯纳学院',['Claremont McKenna College','Claremont McKenna','CMC']],
 ['哈维穆德学院',['Harvey Mudd College','Harvey Mudd','HMC']],
 ['巴纳德学院',['巴纳德','Barnard College','Barnard']],
 ['罗德岛设计学院',['罗德岛设计','RISD','Rhode Island School of Design']],
 ['帕森斯设计学院',['帕森斯','Parsons','Parsons School of Design','Parsons The New School for Design']],
 ['纽约视觉艺术学院',['纽约视觉艺术','School of Visual Arts','SVA']],
 ['芝加哥艺术学院',['School of the Art Institute of Chicago','SAIC']],
 ['普瑞特艺术学院',['普瑞特','普拉特学院','Pratt Institute','Pratt']],
 ['加州艺术学院（CalArts）',['加州艺术学院','CalArts','California Institute of the Arts']],
 ['加州艺术学院（CCA）',['California College of the Arts','CCA']],
 ['萨凡纳艺术与设计学院',['萨凡纳','萨凡纳艺术设计学院','SCAD','Savannah College of Art and Design']],
 ['伯克利音乐学院',['Berklee College of Music','Berklee']],
 ['茱莉亚学院',['茱莉亚','朱莉亚学院','Juilliard','The Juilliard School']],
];
function key(value:string){return value.normalize('NFKC').toLowerCase().replace(/[\s.,，。·’'“”"\-–—()（）]/g,'');}
const lookup=new Map(entries.flatMap(([canonical,aliases])=>[canonical,...aliases].map(alias=>[key(alias),canonical] as const)));
export function normalizeUniversity(value:string){const clean=value.trim();return lookup.get(key(clean))||clean;}
export function parseUniversities(value:string){
 // Resolve full institution names before splitting commas (e.g. UC names).
 return [...new Set(value.split(/[、;；\n/|]+/).flatMap(part=>{
  const clean=part.trim();if(!clean)return [];
  const known=lookup.get(key(clean));if(known)return [known];
  return clean.split(/[,，]+/).map(x=>x.trim()).filter(Boolean).map(normalizeUniversity);
 }))];
}
