import { NextResponse } from "next/server";
import { getDb } from "@/lib/db";
import { children } from "@/db/schema";
import { runInference } from "@/lib/inference";
import { eq } from "drizzle-orm";
const APP="anthropic/claude-haiku-4-5";
const SYSTEM_PROMPT=`你是HFI家长成长营的美国教育探索顾问。基于孩子八项信息输出严格JSON：{"summary":"一句话画像","directions":[{"category":"人文科学|社会科学|自然科学|艺术中的一个","name":"方向中文名","nameEn":"英文领域名","reason":"结合具体回答的依据","nearTerm":"未来6-12个月可尝试的活动","usPath":"美国体系下的高中课程、大学专业或作品集路径"}],"traits":["特质1","特质2","特质3"]}。必须恰好3个探索方向，每个方向category必须选人文科学、社会科学、自然科学、艺术之一。工程计算机归自然科学，商科归社会科学，设计归艺术。梦想职业为空表示尚未提供，不得推断孩子已经有明确职业目标。建议是探索性意见，不是录取预测或能力定论。`;
function parse(raw:string){const s=raw.indexOf("{");const e=raw.lastIndexOf("}");if(s<0||e<0)throw Error("AI返回格式异常");return JSON.parse(raw.slice(s,e+1));}
export async function POST(req:Request){try{const body=await req.json();const keys=["englishName","age","dreamSchool","interests","activities","selfDescription","parentObservation"];const labels:Record<string,string>={englishName:"英文名",age:"年龄",dreamSchool:"梦想学校",interests:"兴趣",activities:"喜欢的活动",selfDescription:"孩子自我描述",parentObservation:"家长观察"};const missing=keys.filter(k=>body[k]==null||!String(body[k]).trim());if(missing.length)return NextResponse.json({error:"请填写："+missing.map(k=>labels[k]).join("、")+"（梦想职业为选填）"},{status:400});if(typeof body.submissionKey!=='string'||!/^[0-9a-f-]{36}$/i.test(body.submissionKey))return NextResponse.json({error:'提交标识无效，请刷新页面重试'},{status:400});
const age=Number(body.age);if(!Number.isInteger(age)||age<1||age>100)return NextResponse.json({error:'请输入有效年龄'},{status:400});
const input={englishName:String(body.englishName).trim(),age,dreamSchool:String(body.dreamSchool).trim(),interests:String(body.interests).trim(),activities:String(body.activities).trim(),selfDescription:String(body.selfDescription).trim(),parentObservation:String(body.parentObservation).trim(),dreamCareer:String(body.dreamCareer??" ").trim()};
const [row]=await getDb().insert(children).values({...input,submissionKey:body.submissionKey}).onConflictDoNothing({target:children.submissionKey}).returning();
if(!row){const [existing]=await getDb().select().from(children).where(eq(children.submissionKey,body.submissionKey));return NextResponse.json({childId:existing?.id,duplicate:true,warning:'问卷已经保存，无需重复提交；画像状态请在活动全景查看。'});}
try{const task=await runInference(APP,{text:JSON.stringify(input),system_prompt:SYSTEM_PROMPT});const out=task.output as {response?:string}|null;const a=parse(out?.response||"");const [updated]=await getDb().update(children).set({aiDirections:JSON.stringify(a.directions||[]),aiTraits:JSON.stringify(a.traits||[]),aiSummary:a.summary||""}).where(eq(children.id,row.id)).returning();return NextResponse.json(updated);}catch(aiError){return NextResponse.json({warning:"问卷已入库，但 AI 分析未完成。工作人员可在活动全景点击开始分析。",childId:row.id},{status:202});}}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"提交失败"},{status:500});}}
