"use client";

import { useState } from "react";
import Link from "next/link";
import { SiteNav } from "@/components/site-nav";
import { useInferenceRun } from "@/lib/use-inference-run";
import * as XLSX from "xlsx";
import QRCode from "qrcode";

const APP = "anthropic/claude-haiku-4-5";
const SYSTEM_PROMPT = `你是HFI家长成长营的教育顾问。根据孩子的英文名、梦想学校和回答，输出 JSON：{"directions":[{"name":"方向","reason":"理由","path":"美国体系下的简短路径"}],"traits":["特质1","特质2"]}。只输出JSON。`;

type Analysis = { directions?: {name:string;reason:string;path:string}[]; traits?: string[] };
function parseJson(raw: string): Analysis | null { try { const s=raw.indexOf("{"); const e=raw.lastIndexOf("}"); return s>=0?JSON.parse(raw.slice(s,e+1)):null; } catch { return null; } }

const schools = [{name:"Stanford University", city:"California", count:12, x:75,y:34}, {name:"RISD", city:"Rhode Island", count:8, x:86,y:26}, {name:"NYU", city:"New York", count:15, x:88,y:33}, {name:"Parsons", city:"New York", count:7, x:88,y:33}, {name:"UCLA", city:"California", count:10, x:73,y:43}];

export default function Page() {
 const [text,setText]=useState(""); const [result,setResult]=useState<Analysis|null>(null); const [bulk,setBulk]=useState(""); const [file,setFile]=useState<File|null>(null); const [qr,setQr]=useState(""); const [message,setMessage]=useState(""); const {loading,error,run}=useInferenceRun();
 async function importRows(rows:unknown[]){const r=await fetch('/api/children/bulk',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(rows)});const j=await r.json();setMessage(r.ok?`已导入 ${j.count} 条记录`:j.error)}
 async function importExcel(){if(!file)return;const book=XLSX.read(await file.arrayBuffer());const rows=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]]);await importRows(rows)}
 async function importText(){const rows=bulk.trim().split(/\n\n+/).map(block=>{const v=block.split(/\n|\t/);return {englishName:v[0],age:v[1],dreamSchool:v[2],interests:v[3],activities:v[4],selfDescription:v[5],parentObservation:v[6],dreamCareer:v[7]}});await importRows(rows)}
 async function makeQR(){setQr(await QRCode.toDataURL(`${location.origin}/register`))}
 async function analyze(){ const task=await run(APP,{text,system_prompt:SYSTEM_PROMPT}); const out=task.output as {response?:string}|null; setResult(parseJson(out?.response||"")); }
 return <main className="min-h-screen bg-[#f4f0e6] text-[#17382f]">
  <header className="mx-auto flex max-w-7xl items-center justify-between px-8 py-7"><div className="text-xl font-semibold tracking-[.18em]">HFI <span className="font-normal tracking-[.08em]">家长成长营</span></div><SiteNav /><Link href="/register" className="border border-[#17382f] px-5 py-2 text-sm">开始录入 →</Link></header>
  <section id="about" className="mx-auto grid max-w-7xl gap-16 px-8 pb-24 pt-16 md:grid-cols-[1.05fr_.95fr] md:items-center"><div><p className="mb-6 text-xs uppercase tracking-[.35em] text-[#8b6f45]">HFI · 2026 FAMILY GROWTH CAMP</p><h1 className="max-w-2xl text-5xl font-light leading-[1.12] tracking-tight md:text-7xl">让每个孩子的<br/><i className="font-serif">可能性</i> 被看见。</h1><p className="mt-8 max-w-lg text-lg leading-8 text-[#50645b]">一场关于兴趣、潜能与未来方向的共同探索。我们从真实的回答出发，勾勒孩子独一无二的成长画像。</p><div className="mt-10 flex gap-4"><Link href="/register" className="bg-[#1e4b3b] px-7 py-4 text-sm text-white" style={{ color: "#ffffff" }}>为孩子建立成长档案　→</Link><a href="/explore" className="border border-[#aeb7ad] px-7 py-4 text-sm">查看活动全景</a></div></div><div className="relative min-h-[390px] overflow-hidden bg-[#dce4d9]"><div className="absolute inset-0 opacity-70" style={{backgroundImage:'radial-gradient(#829b8a 1px,transparent 1px)',backgroundSize:'24px 24px'}}/><div className="absolute left-[18%] top-[22%] h-64 w-64 rounded-full border border-[#829b8a]"/><div className="absolute right-[10%] top-[14%] h-44 w-44 rounded-full border border-[#829b8a]"/><div className="absolute bottom-10 left-10 text-8xl font-serif text-[#315d49]/20">∞</div><div className="absolute bottom-10 right-10 text-right"><div className="text-xs tracking-[.25em] text-[#667d70]">GROWTH IS A JOURNEY</div><div className="mt-2 text-3xl font-serif">成长，是一条路。</div></div></div></section>
  <section className="border-y border-[#d6d2c7] bg-[#f8f5ed] py-16"><div className="mx-auto grid max-w-7xl gap-8 px-8 md:grid-cols-4"><div><div className="text-4xl font-light">X</div><p className="mt-2 text-sm text-[#68786e]">参与家庭</p></div><div><div className="text-4xl font-light">X</div><p className="mt-2 text-sm text-[#68786e]">梦想院校</p></div><div><div className="text-4xl font-light">X</div><p className="mt-2 text-sm text-[#68786e]">发展方向</p></div><div><div className="text-4xl font-light">∞</div><p className="mt-2 text-sm text-[#68786e]">种可能性</p></div></div></section>
  <section id="entry" className="mx-auto max-w-7xl px-8 py-24"><div className="grid gap-14 md:grid-cols-2"><div><p className="text-xs tracking-[.3em] text-[#8b6f45]">AI GROWTH PORTRAIT</p><h2 className="mt-3 text-4xl font-light">试着描述你的孩子</h2><p className="mt-5 leading-7 text-[#607168]">输入孩子的英文名、梦想学校，以及你最想让我们了解的一些回答。AI 会为你生成一份初步的成长方向建议。</p><Link href="/register" className="mt-8 inline-block border-b border-[#1e4b3b] pb-2 text-sm">完整录入孩子信息 →</Link></div><div className="border border-[#d6d2c7] bg-[#f8f5ed] p-7"><textarea value={bulk} onChange={e=>setBulk(e.target.value)} placeholder="批量录入：每个孩子一组，前7项必填，第8项梦想职业可省略；孩子之间空一行" className="mb-5 h-28 w-full resize-none border border-[#c9cfc6] bg-transparent p-3 outline-none"/><div className="mb-6 flex flex-wrap gap-3"><button onClick={importText} className="bg-[#1e4b3b] px-4 py-2 text-xs text-white">批量文本入库</button><label className="border border-[#aeb7ad] px-4 py-2 text-xs">上传 Excel<input type="file" accept=".xlsx,.xls" className="hidden" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button onClick={importExcel} disabled={!file} className="border border-[#aeb7ad] px-4 py-2 text-xs disabled:opacity-40">解析并入库</button><button onClick={makeQR} className="border border-[#aeb7ad] px-4 py-2 text-xs">生成手机问卷二维码</button></div>{qr&&<img src={qr} alt="手机问卷二维码" className="mb-5 h-32 w-32"/>}{message&&<p className="mb-4 text-sm text-[#8b6f45]">{message}</p>}<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="例如：Emma 喜欢画画和讲故事，她梦想进入 RISD……" className="h-32 w-full resize-none border-b border-[#c9cfc6] bg-transparent py-2 outline-none placeholder:text-[#9aa59c]"/><button onClick={analyze} disabled={loading||!text} className="mt-6 bg-[#1e4b3b] px-6 py-3 text-sm text-white disabled:opacity-50">{loading?'正在生成画像…':'生成成长方向　→'}</button>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}{result&&<div className="mt-7 border-t border-[#d6d2c7] pt-5">{result.directions?.map(d=><div key={d.name} className="mb-4"><b>{d.name}</b><p className="mt-1 text-sm text-[#68786e]">{d.reason} · {d.path}</p></div>)}</div>}</div></div></section>
  <footer className="border-t border-[#d6d2c7] px-8 py-8 text-center text-xs tracking-[.2em] text-[#718077]">HFI FAMILY GROWTH CAMP · 2024</footer>
 </main>;
}
